language: python
python:
  - "2.7"
  - "3.5"



before_script:
# Qt needs a display for some of the tests, and it's only run on the system site packages install
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install pylint pylama pylama-pylint mccabe


script:

  - py.test  --pylama --cov-config .coveragerc


after_success:
  - coveralls
