language: python
sudo: required
dist: trusty
python:
 # - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

before_script:
# Qt needs a display for some of the tests, and it's only run on the system site packages install
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install python-coveralls
  - pip install pylint pylama pylama-pylint mccabe


script:

  - py.test  --pylama --cov-config .coveragerc


after_success:
  - coveralls
